INSERT INTO USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('user1', 'login1', 'user@yandex.ru', '2000-12-12');

INSERT INTO USERS(NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('user2', 'login2', 'user@yandex.ru', '2000-12-12');

INSERT INTO USERS(NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('user3', 'login3', 'user@yandex.ru', '2000-12-12');

INSERT INTO FRIENDSHIP(USER_ID, FRIEND_ID)
VALUES ('1', '2');

INSERT INTO FRIENDSHIP(USER_ID, FRIEND_ID)
VALUES ('3', '2');

INSERT INTO FILM(NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA)
VALUES ('film1', 'descr1', '2020-10-10', '120', '1', '1');

INSERT INTO FILM(NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA)
VALUES ('film2', 'descr2', '2020-10-10', '120', '2', '1');

INSERT INTO LIKES (FILM_ID, USER_ID)
VALUES ('1', '1');
